### ISSUE TITLE
[FR]: Shortcut for Switching between (favourite?) Voices / Languages

### ISSUE THREAD

**Issue by LordDerMoff** [ImperialSquid/zotero-zotts#102]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/ImperialSquid/zotero-zotts/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/ImperialSquid/zotero-zotts/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I have read through the [changelog](https://github.com/ImperialSquid/zotero-zotts/blob/main/docs/CHANGELOG.md) to confirm the feature doesn't already exist.
- [X] I have read through the [roadmap](https://github.com/ImperialSquid/zotero-zotts/blob/main/docs/ROADMAP.md) to confirm the feature isn't already planned. (Note - you can still open a feature request if you think the feature should have a higher priority/should be implemented differently/etc!)
- [X] I have described the feature request with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### Feature or improvement you want

A Shortcut to switch between different Voices/Languages. Pressing Ctrl + L (or anything, really) could switch to another installed Voice. 
Preferably only between Voices which have been starred in the setting (but this would be another feature request I guess)

### Why should this be added?

I guess most people read papers minimum in their native language and english. (My Library for example contains 3 different languages)
But as the Voices are tailored to a specific Language, they sound horribly distorted if used in another.

Granted, it is possible to go through the list in the settings and choose the right voice/language. Doable for each specific pdf, but this is cumbersome when you only want to hear the abstracts in the library.
But to function properly, one would have to select favourite voices first - not to sort through the whole list each time with the shortcut. So maybe more complicated than it might seem.

Anyhow, thanks for this plugin!
Cheers

**Comment by ImperialSquid** [comment]
Hmm, I definitely think it's a good idea to allow multiple voice favourites/switching between them/etc. However, I'm a bit reluctant to add it as the _default_ behaviour since I'm keen for ZoTTS to remain as simple to use as possible for most people.

I think I'd be ok with adding it as an advanced feature (down at the bottom of the preferences with substitutions), there you could see a list of current favourites, add or remove them, and specify a shortcut key.

Something like this:
![Screenshot_20240916_174833_Joplin.jpg](https://github.com/user-attachments/assets/afc68b70-bb74-4c05-b939-3a1da2bdea51)

Would that work for you?

**Comment by LordDerMoff** [comment]
I didn't think about the complexity it would add. Still i think it would be a very useful feature if its placed as an advanced setting.

Your sketch looks good, its simple but effective! That's exactly what i had in mind, I cant think about something to add 👍

**Comment by ImperialSquid** [comment]
Hi @LordDerMoff, apologies for the delay (lots of stuff going on, no rest for the wicked lol)

Favourites should now be in the latest version of ZoTTS! (your plugin will update automatically so you shouldn't need to do anything)

Let me know everything works well for you or if you run into any issues.
