### ISSUE TITLE
[Bug]: Failed to load TTS engine (macOS Sequoia)

### ISSUE THREAD

**Issue by egli-nina** [ImperialSquid/zotero-zotts#124]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/ImperialSquid/zotero-zotts/issues) issues to see if someone else has already submitted the same bug report. (Note - if the bug report is about ZoTTS failing to start, please ignore this step and open a report anyway, start up failures can have various causes so it's easier to have separate issues for each, *especially* Linux users)
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/ImperialSquid/zotero-zotts/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I have described the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain paper, I will include its details.

### Zotero version

7.0.7

### ZoTTS version

1.3.0

### OS

Mac

### OS (specific)

macOS Sequoia 15.0.1

### Steps to reproduce

1. Installed the ZoTTS plugin.
2. Closed and reopened Zotero.
3. Restarted computer just in case.
4. Checked that voices appeared in https://mdn.github.io/dom-examples/web-speech-api/speak-easy-synthesis/ - they do.

### Expected behaviour

Open with ZoTTS GUI buttons available.

### Actual behaviour

Zotero opens with a dialog box that states, "ZoTTS, ERROR: ZoTTS failed to load TTS engines. Please submit a bug report for assistance." The GUI buttons for ZoTTS are also missing.

**Comment by ImperialSquid** [comment]
Hi @egli-nina, thanks for your bug report! 

Can you navigate to the error console, from the top navigation bar click `Tools > Developer > Error Console`.

In the text box at the bottom, paste in the following lines and let me know what values you see for each: 
- `Zotero.ZoTTS.data.tts.engines["web speech"].status`
- `Zotero.ZoTTS.data.tts.engines["web speech"].errorMsg`

**Comment by egli-nina** [comment]
Hello @ImperialSquid! Thanks for developing this :)

Both lines yield
`TypeError: Zotero.ZoTTS.data.tts.engines.webSpeech is undefined`
upon typing and
```
Uncaught TypeError: Zotero.ZoTTS.data.tts.engines.webSpeech is undefined
    <anonymous> debugger eval code:1
    getEvalResult resource://devtools/server/actors/webconsole/eval-with-debugger.js:238
    evalWithDebugger resource://devtools/server/actors/webconsole/eval-with-debugger.js:166
    evaluateJS resource://devtools/server/actors/webconsole.js:940
    evaluateJSAsync resource://devtools/server/actors/webconsole.js:846
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
```
upon entering.

**Comment by egli-nina** [comment]
Hello @ImperialSquid! Thanks for developing this :)

Both lines yield
`TypeError: Zotero.ZoTTS.data.tts.engines.webSpeech is undefined`
upon typing and
```
Uncaught TypeError: Zotero.ZoTTS.data.tts.engines.webSpeech is undefined
    <anonymous> debugger eval code:1
    getEvalResult resource://devtools/server/actors/webconsole/eval-with-debugger.js:238
    evalWithDebugger resource://devtools/server/actors/webconsole/eval-with-debugger.js:166
    evaluateJS resource://devtools/server/actors/webconsole.js:940
    evaluateJSAsync resource://devtools/server/actors/webconsole.js:846
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
```
upon entering.

**Comment by ImperialSquid** [comment]
I believe I've found and solved the issue, just going to do some more testing to be sure but a fix should be released soon! 😊

**Comment by egli-nina** [comment]
Awesome, thank you for the fix and the super speedy answers!

**Comment by ImperialSquid** [comment]
Hi @egli-nina, thanks for your patience.

The bug should be resolved now so you should be able to use ZoTTS!

Let me know if you run into any further issues.

**Comment by egli-nina** [comment]
Works perfectly, thank you very much!
