### ISSUE TITLE
[Bug]: in-text citations not ignored/substituted

### ISSUE THREAD

**Issue by petercla0119** [ImperialSquid/zotero-zotts#132]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/ImperialSquid/zotero-zotts/issues) issues to see if someone else has already submitted the same bug report. (Note - if the bug report is about ZoTTS failing to start, please ignore this step and open a report anyway, start up failures can have various causes so it's easier to have separate issues for each, *especially* Linux users)
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/ImperialSquid/zotero-zotts/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I have described the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain paper, I will include its details.

### Zotero version

7.0.3

### ZoTTS version

1.4.0

### OS

Mac

### OS (specific)

macOS Sonoma 14.6.1 (23G93)

### Steps to reproduce

1. Open zotero application
2. click on settings from dropdown menu
3. navigate to ZoTTS in the panel on the left
4. scroll to Substitutions section under Advanced options
5. click checkbox to remove citations

### Expected behaviour

After restarting Zotero, I would expect in-text citations to be ignored when speaking

### Actual behaviour

After restarting, the in-text citations are spoken. The Remove "parenthetical" style citations checkbox is unchecked after closing the Settings dialog window in Zotero despite having previously checked the box.

**Comment by ImperialSquid** [comment]
Hi @petercla0119, thanks for your bug report! 

A couple of questions:
- Do you have any other substitutions active or just parentheticals? (Both built in and custom ones in the text box) 
- In the settings:
    - Go to the Advanced pane
    - Scroll down to the Config Editor
    - (proceed through the warning if it comes up)
    - Search for ZoTTS in the search bar
    - Let me know what value you see listed next to `extensions.zotero.ZoTTS.subs.removeParenCitations`
- Also, with the Config Editor still open, do you see the value change as you toggle the checkbox to remove parentheticals?
- Do the checkbox and Config Editor value still match after restarting?
- Lastly, does this problem only happen on some papers or is it all of them?
    - And can you let me know what papers you tried in either case?

(Sorry, I know this is a lot of questions lol)

**Comment by petercla0119** [comment]
Thanks so much for creating this and for your reply! I resolved the issue with your help, but  I answer your questions (below) for the sake of completion: 
I just had parentheticals.
I followed your instructions in the settings window and changed the value to "true" which also changed toggled the checkbox. 
The checkbox and config editor values indeed match after restarting Zotero. 
The issue was happening on all papers, but appears to be resolved with your guidance! 

Thanks again!  I really appreciate your time to develop this tool!

**Comment by ImperialSquid** [comment]
Glad to hear the issue was resolved!

It's very strange that the checkbox and settings value managed to become desynchronised, but I guess it's not something to worry about since it's resolved now! 

Let me know if you run into any further issues/have feature requests/etc! 😁
