### ISSUE TITLE
[Question]: Regex to correct currency pronunciation?

### ISSUE THREAD

**Issue by v4u6h4n** [ImperialSquid/zotero-zotts#135]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/ImperialSquid/zotero-zotts/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/ImperialSquid/zotero-zotts/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I have read through the [changelog](https://github.com/ImperialSquid/zotero-zotts/blob/main/docs/CHANGELOG.md) to confirm the feature doesn't already exist.
- [X] I have read through the [roadmap](https://github.com/ImperialSquid/zotero-zotts/blob/main/docs/ROADMAP.md) to confirm the feature isn't already planned. (Note - you can still open a feature request if you think the feature should have a higher priority/should be implemented differently/etc!)
- [X] I have described the feature request with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### Feature or improvement you want

Can you make a discussions section available for the repo? I have some dumb questions about pronunciation and regex that I dont want clogging up the issues section of the repo.

**Comment by ImperialSquid** [comment]
Eh, given ZoTTS isn't a huge project I don't think you're drowning out other discussions and/or at risk of being buried, other than your comment the other day, the most recent activity in the issues was a week ago lol. I'm also hesitant to split up the conversations in case someone else has the same questions you do, it's just one more place to search for not that much gain...

That said, I'm happy to answer any and all questions you have here! 😊

**Comment by v4u6h4n** [comment]
Okay cool :-)

I'm just wondering what regex to use to allow, for example, the pronunciation of `$100` (or any dollar amount), so that it is pronounced `one hundred dollars` instead of `dollar one hundred`.

**Comment by ImperialSquid** [comment]
No worries! 

For that I think `/\$([0-9\.]+)/:"\1 dollars"` should work. (Just paste it directly into the substitutions box, including slashes and quotes).

Technically this will turn `$100` into `"100 dollars"` not `"one hundred dollars"`, I'm sure number to text transliteration is possible in regex, I'm just not sure how off the top of my head lol

---

As an explanation in case you're not familiar: 

`$` looks for dollar symbols, however a `$` on its own is a special character in regex that normally does something different so we use `\$` to tell it to look for a _literal_ dollar symbol. 

`[0-9\.]` looks for any characters that are the digits 0 to 9 _or_ a literal full stop(/period) character. `[0-9\>]+` tells it to find _at least one_ of those characters. 

The curved brackets around it, `([0-9\.]+)`, turn it into a capture group, which basically says "hey, hold onto anything you find that matches the bit of pattern in this group".

In the replacement part `"\1 dollars"`, the `\1` tells it to replace this with the first (and in this case only) capture from the pattern. 

So, for example, the following substitutions should work: 
- $4 -> 4 dollars
- $100 -> 100 dollars
- $3.14 -> 3.14 dollars

**Comment by v4u6h4n** [comment]
Thanks! Okay that makes sense. It doesnt seem to be working for me however, so I'm either doing something wrong, or the regex on the actual pronunction side isn't being processed as regex, causes its just saying "1 dollars". Can the pronunciation side handle regex?

**Comment by ImperialSquid** [comment]
ZoTTS handles the regex before passing it to the TTS engine, so this should work on all platforms.

Turns out I was just being dumb lol, it's `$1` not `\1` to reuse a capture group, so `/\$([0-9\.]+)/:"$1 dollars"` is the correct substitution!

**Comment by v4u6h4n** [comment]
Perfect! Thanks!
