### ISSUE TITLE
[Bug]: Copy bibliography ends playback

### ISSUE THREAD

**Issue by v4u6h4n** [ImperialSquid/zotero-zotts#141]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/ImperialSquid/zotero-zotts/issues) issues to see if someone else has already submitted the same bug report. (Note - if the bug report is about ZoTTS failing to start, please ignore this step and open a report anyway, start up failures can have various causes so it's easier to have separate issues for each, *especially* Linux users)
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/ImperialSquid/zotero-zotts/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I have described the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain paper, I will include its details.

### Zotero version

7.0.10

### ZoTTS version

1.4.0

### OS

Linux

### OS (specific)

Arch

### Steps to reproduce

1. Begin playback.
2. Use the copy bibliography shortcut or menu item.

### Expected behaviour

Playback to continue.

### Actual behaviour

Playback stops and cannot be resumed.

**Comment by ImperialSquid** [comment]
Thanks for the bug report @v4u6h4n.

> Use the copy bibliography ... menu item.

I can't replicate this behaviour.

But in any case, this is just a matter of two shortcuts using the same letter. 

As [mentioned in the README](https://github.com/ImperialSquid/zotero-zotts#shortcuts), Ctrl + Shift + C is the shortcut to cancel. But this is editable from the [preferences](https://github.com/ImperialSquid/zotero-zotts#preferences).

![Screenshot 2024-12-08 070809](https://github.com/user-attachments/assets/8c589941-3127-49ed-8a28-7d79c48ac31e)

The Zotero "Copy Bibliography" shortcut is also editable, under `Advanced > Shortcuts`.

You either need to change the Zotero shortcut, or the ZoTTS one... 🤷‍♂️

**Comment by v4u6h4n** [comment]
Ohhhh... oops...

>_> *blush*

...thanks :-)

**Comment by ImperialSquid** [comment]
No worries, happy to help!
