### ISSUE TITLE
[Question]: How add a pause to a pronounciation?

### ISSUE THREAD

**Issue by v4u6h4n** [ImperialSquid/zotero-zotts#142]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/ImperialSquid/zotero-zotts/issues) issues to see if someone else has already submitted the same bug report. (Note - if the bug report is about ZoTTS failing to start, please ignore this step and open a report anyway, start up failures can have various causes so it's easier to have separate issues for each, *especially* Linux users)
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/ImperialSquid/zotero-zotts/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I have described the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain paper, I will include its details.

### Zotero version

7.0.11

### ZoTTS version

1.4.0

### OS

Linux

### OS (specific)

arch

### Question

How do I add a pause in a pronounciation substitution? Currently I am substituting `”` with `end-quote`, but adding a space or a space and comma doesn't seem to be producing a pause before the `end-quote` is spoken, for example using something like this: `"”":", end-quote"` or  `"”":" end-quote"`. Any suggestions?

**Comment by ImperialSquid** [comment]
Thanks for the question @v4u6h4n,

Hmm, I'm not immediately sure honestly... 

Since normally a full stop(/period) or ellipsis indicate a bigger pause in speech would of those work better? For example, either of:
- "”":". end-quote"
- "”":"... end-quote"

**Comment by v4u6h4n** [comment]
Ah, hadnt thought of the `...`, that did the trick. Thanks!
