### ISSUE TITLE
How to use zotts?

### ISSUE THREAD

**Issue by nzq1224** [ImperialSquid/zotero-zotts#30]
First of all, thanks to the author for sharing. I really need TTS feature to learn English while reading literature better, but I don't know how to use zotts

**Comment by ImperialSquid** [comment]
Hi!

Thanks for your interest!

Unfortunately Zotts is still in construction so it's not quite available yet*

As an alternative, most web browsers are able to open PDFs and also have TTS plugins, if you right click a paper and open it online, you should be able to get TTS working there instead

Hope that helps!

I'm going to close this issue but let me know if you need further assistance, alternatively there's the [Zotero forums](https://forums.zotero.org/discussions/)



*The long technical explanation is that the method I had planned for implementing TTS isn't available in Zotero 6, I've talked to the Zotero dev team and it should be available in Zotero 7 but I don't have a timeline on that. I'm currently looking into ways to use TTS in Z6 but it looks to be very complicated...

**Comment by nzq1224** [comment]
Thank you very much for your reply!

I understand the situation now. Sincerely hope your development work goes well and look forward to seeing it .
