### ISSUE TITLE
Release v1.1.1

### ISSUE THREAD

**Issue by GUGU75006** [ImperialSquid/zotero-zotts#75]
In version [Release v1.1.0](https://github.com/ImperialSquid/zotero-zotts/releases/tag/v1.1.0)
there was a Zotero parameter but the voice selector wasn't working.
![image](https://github.com/user-attachments/assets/01429231-f263-4622-a0f7-4d901126d370)

now in version v1.1.1
we can't see the parameters.
![image](https://github.com/user-attachments/assets/6a7a9640-c02d-412f-818a-5bc57ed6cab0)

**Comment by ImperialSquid** [comment]
Preference panes might take a moment to load, does closing and reopening the preferences fix the issue?

**Comment by GUGU75006** [comment]
In fact it does load after a time, but the test voice and other speak aloud doesn't work 
<img width="784" alt="image" src="https://github.com/user-attachments/assets/b7697709-7ee0-434e-afc9-ba6a3a3c4789">
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/c452fc24-c8c8-4f52-9da2-531eac9a4778">
<img width="307" alt="image" src="https://github.com/user-attachments/assets/c60d0133-1b5d-463e-be51-98b6f988d709">

**Comment by ImperialSquid** [comment]
If that doesn't work, you can try sending me your logs: 

1. Go to Help > Debug Output Logging > Restart with Logging Enabled...
2. Do what you did before when the problem happened
3. Go to Help > Debug Output Logging > View Output
4. Click Save and save the output somewhere
5. Zip the files 
6. Email them to me

**Comment by GUGU75006** [comment]
Its started to work somehow. It might be due to my shitty computer.

**Comment by ImperialSquid** [comment]
Nah it's not just you, I've had two other people report slow loading (one Linux, the other Mac, so I suspect it's a Unix problem), they all seem to be really slow to load this particular voice engine, but are fine when it gets started...

I'll add a note to the main page about giving it a moment to load/trying closing and reopening/etc, just in case any future people get confused... 🤷

ZoTTS is also designed to be able to work with other engines in the future so maybe it won't be an issue so much when those get implemented.

Anyway, I'll close the issue now, let me know if you have any more trouble.
