### ISSUE TITLE
[Bug]: ZoTTS failed to load (NixOS)

### ISSUE THREAD

**Issue by ImperialSquid** [ImperialSquid/zotero-zotts#99]
> I got the same bug too (after trying to install it for the first time). And there are 6 voices listed in the dropdown normally for me.
> 
> I used Zotero 7.0 on NixOS btw (`zotero --version` gave `Zotero Zotero 115.9.1esr`)

_Originally posted by @HynDuf in https://github.com/ImperialSquid/zotero-zotts/issues/98#issuecomment-2328849970_

**Comment by ImperialSquid** [comment]
(Small disclaimer, I'm not a linux user so forgive me if solving this is slow/painful lol, not my area of expertise)

Firstly, are you using Zotero in flatpak/some other sandboxed environment? 

As mentioned in [this issue (comment)](https://github.com/ImperialSquid/zotero-zotts/issues/74#issuecomment-2250961909), Firefox (which Zotero is based on) was [missing support for speech-dispatcher until version 123](https://bugzilla.mozilla.org/show_bug.cgi?id=1638150) (Z7 is based on v115 ESR)

**Comment by HynDuf** [comment]
If nix is considered a sandboxed envionment itself then yes. But it's not flatpack, I installed using the nix package manager.

**Comment by ImperialSquid** [comment]
Hmm... From some googling it looks like it is? 

Given that this isn't my area of expertise, and any solution likely involves changes to programs outside of ZoTTS anyway, I'd recommend posting to the [NixOS forums](https://discourse.nixos.org/) or [Zotero forums](https://forums.zotero.org/) instead, they're likely to know what to do better than I do... (Though of course, I'm happy to make changes here if need be)

Sorry I couldn't be more helpful...!

**Comment by HynDuf** [comment]
Yeah and `window.speechSynthesis.getVoices()` gave `[]` even after running multiple times.

Besides, when loading the plugin it gave `Missing chrome or resource URL: chrome://global/skin/browser.css` (to the terminal where I run `zotero`).

**Comment by ImperialSquid** [comment]
Yeah definitely seems to be something outside of my wheelhouse then, sorry again though 

Also fyi, that missing css isn't a ZoTTS thing (in fact the plugin doesn't use any css files, what little styling that is used is hard coded lol)

**Comment by ImperialSquid** [comment]
Closed as upstream

Fixes might be possible, but are almost certainly non-trivial and definitely outside the scope of ZoTTS
